logo = "img/compsoc-logo-sticker.png"
colorScheme = "fire"

enableSearch = false
enableCodeCopy = true

[header]
  layout = "floating" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur, floating
  mobileMenuStyle = "dropdown" # valid options: fullscreen, dropdown

[homepage]
  layout = "landing" # valid options: page, profile, hero, card, background, landing, custom
  homepageImage = "img/background.jpg"

[article]
  showDate = false
  showAuthor = false
  showWordCount = false
  showReadingTime = false
  showPagination = false

[author]
  name = "LUCompSoc"
  image = "img/compsoc-logo-normal.png"
